// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1:string):Promise<string>;

export function Encrypt(arg1:string):Promise<string>;

export function PKCS5Padding(arg1:Array<number>,arg2:number):Promise<Array<number>>;
