// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1) {
  return ObfuscatedCall(1, [arg1]);
}

export function Encrypt(arg1) {
  return ObfuscatedCall(2, [arg1]);
}

export function PKCS5Padding(arg1, arg2) {
  return ObfuscatedCall(3, [arg1, arg2]);
}
