document.writeln("<meta name=\'wails-options\' content=\'noautoinject\' />");
document.writeln("<link href=\'https://cdn.jsdelivr.net/npm/daisyui@4.6.0/dist/full.min.css\' rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("<link rel=\'stylesheet\' href=\'css/main.css\' />");
document.writeln("<script src=\'https://cdn.tailwindcss.com\'></script>");
document.writeln("<script src=\'js/font-awesome.js\'></script>");
document.writeln("<script src=\'js/utils.js\'></script>");
document.writeln("<script src=\'/wails/ipc.js\'></script>");
document.writeln("<script src=\'/wails/runtime.js\'></script>");
document.writeln("<script src=\'js/loader.js\' type=\'module\'></script>");
document.writeln("<nav class=\'navbar bg-base-100 sticky top-0 left-0 right-0 has-shadow\' style=\'--wails-draggable: drag; z-index: 30;\'>");
document.writeln("    <div class=\'navbar-start pb-1\'>");
document.writeln("        <div class=\'indicator\' style=\'--wails-draggable: none;\'>");
document.writeln("            <span class=\'theme-indicator indicator-item indicator-bottom badge badge-accent\'></span>");
document.writeln("            <button class=\'btn rounded-box text-primary text-xl\' onclick=\'onToggleTheme()\'>");
document.writeln("                <span><strong>吃了吗</strong></span>");
document.writeln("                <span>");
document.writeln("                    <i class=\'fa fa-utensils\'></i>");
document.writeln("                </span>");
document.writeln("            </button>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("    <div class=\'navbar-center\'>");
document.writeln("        <a class=\'btn btn-ghost text-base-content\'>");
document.writeln("            <strong><span id=\'window-title\'></span></strong>");
document.writeln("        </a>");
document.writeln("    </div>");
document.writeln("    <div class=\'navbar-end\'>");
document.writeln("        <div>");
document.writeln("            <button class=\'btn btn-circle btn-outline text-sm text-success\' onclick=\'onMinWindow()\'");
document.writeln("                style=\'font-family: Marlett24; --wails-draggable: none;\'>");
document.writeln("                <strong style=\'font-size: large;\'>0</strong>");
document.writeln("            </button>");
document.writeln("            <button class=\'btn btn-circle btn-outline text-sm text-warning\' onclick=\' onToggleWindow()\'");
document.writeln("                style=\'font-family: Marlett24; --wails-draggable: none;\'>");
document.writeln("                <strong id=\'toggle-button\' style=\'font-size: large;\'>1</strong>");
document.writeln("            </button>");
document.writeln("            <button class=\'btn btn-circle btn-outline text-sm text-error\' onclick=\'onCloseWindow()\'");
document.writeln("                style=\'font-family: Marlett24; --wails-draggable: none;\'>");
document.writeln("                <strong style=\'font-size: large;\'>r</strong>");
document.writeln("            </button>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</nav></br>");
document.writeln("<nav class=\'btm-nav bg-base-100 text-secondary fixed bottom-0 left-0 right-0 has-shadow\' style=\'z-index: 29;\'>");
document.writeln("    <a class=\'nav-btn\' href=\'/index.html\' target=\'_self\'>");
document.writeln("        <i class=\'fa fa-home\'></i>");
document.writeln("        <span class=\'btm-nav-label\'>首页</span>");
document.writeln("    </a>");
document.writeln("    <a class=\'nav-btn\' href=\'/chilema.html\' target=\'_self\'>");
document.writeln("        <i class=\'fa fa-utensils\'></i>");
document.writeln("        <span class=\'btm-nav-label\'>吃了吗</span>");
document.writeln("    </a>");
document.writeln("    <a class=\'nav-btn\' href=\'/unlock-music.html\' target=\'_self\'>");
document.writeln("        <i class=\'fa fa-music\'></i>");
document.writeln("        <span class=\'btm-nav-label\'>音乐解锁</span>");
document.writeln("    </a>");
document.writeln("    <a class=\'nav-btn\' href=\'/sort.html\' target=\'_self\'>");
document.writeln("        <i class=\'fa fa-random\'></i>");
document.writeln("        <span class=\'btm-nav-label\'>排序测试</span>");
document.writeln("    </a>");
document.writeln("    <a class=\'nav-btn\' href=\'/about.html\' target=\'_self\'>");
document.writeln("        <i class=\'fa fa-info-circle\'></i>");
document.writeln("        <span class=\'btm-nav-label\'>关于</span>");
document.writeln("    </a>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <button class=\'btn btn-primary\' onclick=\'onRequestContactUs()\'>");
document.writeln("            <i class=\'fa fa-address-card\'></i>");
document.writeln("            <span class=\'btm-nav-label\'>联系我们</span>");
document.writeln("        </button>");
document.writeln("    </div>");
document.writeln("</nav>");
document.writeln("<script>");
document.writeln("    let themes = [");
document.writeln("        \'light\',");
document.writeln("        \'dark\',");
document.writeln("        \'cupcake\',");
document.writeln("        \'bumblebee\',");
document.writeln("        \'emerald\',");
document.writeln("        \'corporate\',");
document.writeln("        \'synthwave\',");
document.writeln("        \'retro\',");
document.writeln("        \'cyberpunk\',");
document.writeln("        \'valentine\',");
document.writeln("        \'halloween\',");
document.writeln("        \'garden\',");
document.writeln("        \'forest\',");
document.writeln("        \'aqua\',");
document.writeln("        \'lofi\',");
document.writeln("        \'pastel\',");
document.writeln("        \'fantasy\',");
document.writeln("        \'wireframe\',");
document.writeln("        \'black\',");
document.writeln("        \'luxury\',");
document.writeln("        \'dracula\',");
document.writeln("        \'cmyk\',");
document.writeln("        \'autumn\',");
document.writeln("        \'business\',");
document.writeln("        \'acid\',");
document.writeln("        \'lemonade\',");
document.writeln("        \'night\',");
document.writeln("        \'coffe\',");
document.writeln("        \'winter\',");
document.writeln("        \'dim\',");
document.writeln("        \'nord\',");
document.writeln("        \'sunset\',");
document.writeln("    ];");
document.writeln("    (function () {");
document.writeln("        // Get the current title");
document.writeln("        let title = document.title;");
document.writeln("        // Set the window title");
document.writeln("        document.getElementById(\'window-title\').innerHTML = title;");
document.writeln("        // Load theme");
document.writeln("        let theme = loadTheme();");
document.writeln("        // Set theme");
document.writeln("        setTheme(theme);");
document.writeln("        // Loop through all the .nav-btn and active the current one");
document.writeln("        let navBtns = document.querySelectorAll(\'.nav-btn\');");
document.writeln("        navBtns.forEach(function (btn) {");
document.writeln("            // If href is current page");
document.writeln("            if (btn.getAttribute(\'href\') === window.location.pathname) {");
document.writeln("                // Add active class");
document.writeln("                btn.classList.add(\'active\');");
document.writeln("            }");
document.writeln("        });");
document.writeln("        // Get all .fas");
document.writeln("        let nav_btns = document.querySelectorAll(\'.nav-btn\');");
document.writeln("        // If hover on .nav_btns");
document.writeln("        nav_btns.forEach(function (nav) {");
document.writeln("            let fa = nav.querySelector(\'.fa\');");
document.writeln("            nav.addEventListener(\'mouseover\', function () {");
document.writeln("                // Add .hover class");
document.writeln("                fa.classList.add(\'fa-spin\');");
document.writeln("            });");
document.writeln("            nav.addEventListener(\'mouseout\', function () {");
document.writeln("                // Remove .hover class");
document.writeln("                fa.classList.remove(\'fa-spin\');");
document.writeln("            });");
document.writeln("        });");
document.writeln("    })();");
document.writeln("");
document.writeln("    function onToggleTheme() {");
document.writeln("        // Get the current theme");
document.writeln("        let current = getCurrentTheme();");
document.writeln("        // Get the next theme");
document.writeln("        let next = (current + 1) % themes.length;");
document.writeln("        // Set the next theme");
document.writeln("        setTheme(themes[next]);");
document.writeln("        // Save the theme");
document.writeln("        saveTheme();");
document.writeln("    }");
document.writeln("");
document.writeln("    function setTheme(themeName) {");
document.writeln("        let html = document.querySelector(\'html\');");
document.writeln("        html.setAttribute(\'data-theme\', themeName);");
document.writeln("        document.querySelector(\'.theme-indicator\').innerHTML = themeName;");
document.writeln("    }");
document.writeln("");
document.writeln("    function loadTheme() {");
document.writeln("        let themeFromStorage = localStorage.getItem(\'theme\');");
document.writeln("        if (themeFromStorage) {");
document.writeln("            return themeFromStorage;");
document.writeln("        }");
document.writeln("        // Get default theme by os light/dark scheme");
document.writeln("        let osTheme = window.matchMedia(\'(prefers-color-scheme: dark)\').matches ? \'dark\' : \'light\';");
document.writeln("        return (osTheme == \'dark\') ? \'dracula\' : \'winter\';");
document.writeln("    }");
document.writeln("");
document.writeln("    function saveTheme() {");
document.writeln("        let html = document.querySelector(\'html\');");
document.writeln("        let theme = html.getAttribute(\'data-theme\');");
document.writeln("        localStorage.setItem(\'theme\', theme);");
document.writeln("    }");
document.writeln("");
document.writeln("    function getCurrentTheme() {");
document.writeln("        let html = document.querySelector(\'html\');");
document.writeln("        let theme = html.getAttribute(\'data-theme\');");
document.writeln("        return themes.indexOf(theme);");
document.writeln("    }");
document.writeln("</script>");