// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenLinkInExternalBrowser(arg1) {
  return ObfuscatedCall(0, [arg1]);
}
